### ISSUE TITLE
CUDA out of memory.

### ISSUE THREAD

**Issue by PauloKim1246** [vt-vl-lab/FGVC#21]
`RuntimeError: CUDA out of memory. Tried to allocate 3.52 GiB (GPU 0; 15.75 GiB total capacity; 11.38 GiB already allocated; 1.07 GiB free; 11.54 GiB reserved in total by PyTorch)`
(Running on Colab Pro)
What is the minimum required specs to run the current version of FGVC ?

**Comment by GrahamboJangles** [comment]
This thing seriously uses some VRAM! I just tried too, got the same error.

**Comment by xsanders** [comment]
I tried to process a 1080p Video with my TitanX 12GB VRAM and it failed. I have to go down to SD (720x480) to get it running. Are there any strategies for this to work with hires footage ?

**Comment by PauloKim1246** [comment]
> I tried to process a 1080p Video with my TitanX 12GB VRAM and it failed. I have to go down to SD (720x480) to get it running. Are there any strategies for this to work with hires footage ?

Problem solved on the current Google Colab Notebook
[Heres](https://colab.research.google.com/drive/1pb6FjWdwq_q445rG2NP0dubw7LKNUkqc
) the link, i would recommend using colab
